### PR TITLE
README: update link URL

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by lucasvr** [comment]
Thanks, Waldir!

**Comment by waldyrious** [comment]
Thank *you* for all the work you do around this project :) I hope I'll be able to contribute more substantially in the future.

**Comment by waldyrious** [comment]
Oh, on a slightly related note: would it be possible to include a link to the kernel side of GoboHide in the README? I couldn't find a permalink, just the versioned patches like https://github.com/gobolinux/Recipes/blob/master/trunk/Linux/4.9.4/01-gobohide.patch...

**Comment by lucasvr** [comment]
There are a few places where one can get the most recent version of the GoboHide kernel extension:
- http://recipes.gobolinux.org/r/?list=Linux
- https://github.com/gobolinux/Recipes/tree/master/trunk/Linux (as you have found out)
- https://github.com/lucasvr/linux-gobohide

The last item is the tree from where I generate the patch files. I'd say that the two links to GitHub are probably the best ones to include in the README. I will happily merge a PR if you have time to submit one.

**Comment by waldyrious** [comment]
Nice! I'll prepare a PR soon.

**Comment by waldyrious** [comment]
Hmmm... I'm trying to get a smart link that would show the patch's contents rather than the entire repository, but I'm having some trouble doing that. https://github.com/lucasvr/linux-gobohide/compare/master...gobohide doesn't quite work, and neither does https://github.com/torvalds/linux/compare/v4.8-rc1...lucasvr:gobohide. The diff shows a bunch of additional changes, presumably from the two merge commits.

Would https://github.com/lucasvr/linux-gobohide/compare/master...gobohide~2 be appropriate? I don't like to hardcode the relative reference, since that depends on how many non-merge commits your branch has. Is it your preference not to rebase the branch and instead merge upstream back into it?

**Comment by waldyrious** [comment]
Btw, are the past revisions to the patch (particularly [those of gobohide.c](https://github.com/lucasvr/linux-gobohide/blob/gobohide/fs/gobohide.c#L16-L61)) not stored in git? Is there any way they could be restored / recreated for historical interest?

**Pull request merged**
